msg = "Hallo Verden!"
print()
print(msg)
print()
print("Oppgave E 1.1")
print(4*4-4*3*5)
print()
print("Oppgave E 1.2")
print((10.5-5.6) / 0.5)
print()
print("Oppgave E 1.3")
print()
print("* ***** *****")
print("* *   * *   *")
print("* *   * *   *")
print("* *   * *   *")
print("* ***** *****")
print()